import alpha

# API_KEY
api_key = 'FTCAN551TMQBI2IC'

# Core Stock API Function List
TIME_SERIES_INTRADAY = 'TIME_SERIES_INTRADAY'
TIME_SERIES_DAILY = 'TIME_SERIES_DAILY'
TIME_SERIES_WEEKLY = 'TIME_SERIES_WEEKLY'
TIME_SERIES_WEEKLY_ADJUSTED = 'TIME_SERIES_WEEKLY_ADJUSTED'
TIME_SERIES_MONTHLY = 'TIME_SERIES_MONTHLY'
TIME_SERIES_MONTHLY_ADJUSTED = 'TIME_SERIES_MONTHLY_ADJUSTED'


stock_fetch = alpha.CoreStock(api_key)
df = stock_fetch.stock_df('IBM', TIME_SERIES_INTRADAY)
print(df.head())